name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest
        
    - name: Install dependencies
      run: |
        if [ -f "pnpm-lock.yaml" ]; then
          echo "Lockfile found, using frozen install"
          pnpm install --frozen-lockfile
        else
          echo "No lockfile found, installing without frozen lockfile"
          pnpm install --no-frozen-lockfile
        fi
      
    - name: Generate Prisma client
      run: pnpm db:generate
      env:
        BETTER_AUTH_SECRET: "ci-test-secret-key-for-build-only"
        DATABASE_URL: "mysql://test:test@localhost:3306/test"
      
    - name: Build UI package
      run: pnpm --filter @quickpoll/ui build
      
    - name: Build web application
      run: pnpm build
      env:
        BETTER_AUTH_SECRET: "ci-test-secret-key-for-build-only"
        DATABASE_URL: "mysql://test:test@localhost:3306/test"
      
    - name: Run tests (if available)
      run: |
        if [ -f "package.json" ] && grep -q '"test"' package.json; then
          pnpm test
        else
          echo "No tests configured, skipping..."
        fi
        
    # Add your deployment steps here
    # Examples:
    # - name: Deploy to Vercel
    #   uses: amondnet/vercel-action@v25
    #   with:
    #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
    #     vercel-org-id: ${{ secrets.ORG_ID }}
    #     vercel-project-id: ${{ secrets.PROJECT_ID }}
    #     working-directory: ./apps/web
    #     
    # - name: Deploy to Docker
    #   run: |
    #     docker build -t quickpoll-app .
    #     docker push your-registry/quickpoll-app:latest
